version: "3.8"
services:
  api:
    build: ./api
    container_name: travel_agency_system_api
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: 'db'
      DB_PORT: 3306
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
    - db

  web:
    build: ./web
    container_name: travel_agency_system_web
    depends_on:
    - api

  db:
    image: mariadb:latest
    container_name: travel_agency_system_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
