services:
  api:
    container_name: test_travel_agency_system_api
    command:
    - /bin/sh
    - -c
    - |
      wait-for-it --service db:3306 --timeout=60
      python manage.py migrate
      python manage.py test
    environment:
      DB_USER: root
      DB_PASS: root
      DB_NAME: travel_agency_system
      DB_HOST: db
      DB_PORT: 3306
      SECRET_KEY: secret-key
    depends_on:
      - db

  #hotel_microservice_test:
  #  build: ./microservices/hotel.service/Tests
  #  container_name: hotel_microservice_test
  #  depends_on:
  #    - hotel_microservice

  db:
    container_name: test_travel_agency_system_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travel_agency_system
