version: "3.8"
services:
  api:
    build: ./api
    container_name: travel_agency_system_api
    command:
    - /bin/sh
    - -c
    - |
      wait-for-it --service db:3306 --timeout=60
      python manage.py migrate
      python manage.py collectstatic --noinput
      python manage.py runserver 0.0.0.0:80
    depends_on:
    - db

  web:
    build: ./web
    container_name: travel_agency_system_web
    ports:
    - 3000:3000
    depends_on:
    - api

  db:
    image: mariadb:latest
    container_name: travel_agency_system_db

  api_gateway:
    build: ./microservices/api.gateway
    container_name: api_gateway
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - 5000:80
    depends_on:
    - db

  user_microservice:
    build: ./microservices/user.service
    container_name: user_microservice
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
    - db

  hotel_microservice:
    build: ./microservices/hotel.service
    container_name: hotel_microservice
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
    - db

  nginx:
    image: nginx:latest
    container_name: travel_agency_system_nginx
    ports:
    - 80:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./api/static:/home/static
    depends_on:
    - api
