services:
  api:
    ports:
    - 8000:80
    volumes:
    - ./api:/app

  web:
    ports:
    - 3000:3000
    volumes:
    - ./web:/app

  db:
    volumes:
    - ./db:/var/lib/mysql
    ports:
    - 3306:3306

volumes:
  db:
