services:
  api:
    image: ghcr.io/aymaneboukrouh/tas-api:latest
    command:
    - /bin/sh
    - -c
    - |
      wait-for-it --service db:3306 --timeout=60
      python manage.py migrate
      python manage.py collectstatic --noinput
      gunicorn travelagency.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:80
    volumes:
    - /home/tas/api_static:/app/static

  web:
    image: ghcr.io/aymaneboukrouh/tas-web:latest

  db:
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
  
  nginx:
    image: nginx:latest
    container_name: travel_agency_system_nginx
    ports:
    - 80:80
    - 443:443
    volumes:
    - /home/tas/nginx.conf:/etc/nginx/nginx.conf
    - /etc/letsencrypt:/etc/letsencrypt
    - /home/tas/api_static:/home/static
    depends_on:
    - api
    - web

volumes:
  api_static:
