services:
  api:
    command:
    - /bin/sh
    - -c
    - |
      wait-for-it --service db:3306 --timeout=60
      python manage.py migrate
      python manage.py collectstatic --noinput
      python manage.py runserver 0.0.0.0:80
    ports:
    - 8000:80
    volumes:
    - ./api:/app

  web:
    build:
      target: base
    command: npm run dev
    ports:
    - 3000:3000
    volumes:
    - ./web:/app

  db:
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
    - ./db:/var/lib/mysql
    ports:
    - 3306:3306

  api_gateway:
    build: ./microservices/api.gateway
    container_name: api_gateway
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - 5000:80
    depends_on:
    - db

  api_gateway:
    build: ./microservices/api.gateway
    container_name: api_gateway
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
    - db
    - user_microservice
    - hotel_microservice

  user_microservice:
    build: ./microservices/user.service
    container_name: user_microservice
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
    - db

  hotel_microservice:
    build: ./microservices/hotel.service
    container_name: hotel_microservice
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
    - db

volumes:
  db:
