version: "3.8"
services:
  api:
    build: ./api
    container_name: travel_agency_system_api
    ports:
    - 8000:80

  web:
    build: ./web
    container_name: travel_agency_system_web
    ports:
    - 3000:3000
    depends_on:
    - api

  db:
    image: mariadb:latest
    container_name: travel_agency_system_db
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
