services:
  api:
    command:
    - /bin/sh
    - -c
    - |
      wait-for-it --service db:3306 --timeout=60
      python manage.py migrate
      python manage.py collectstatic --noinput
      python manage.py runserver 0.0.0.0:80
    ports:
    - 8000:80
    volumes:
    - ./api:/app

  web:
    ports:
    - 3000:3000
    volumes:
    - ./web:/app

  db:
    volumes:
    - ./db:/var/lib/mysql
    ports:
    - 3306:3306

volumes:
  db:
