from core.serializers.hotel_serializer import HotelSerializer
from core.serializers.office_serializer import OfficeSerializer
from core.serializers.reservation_serializer import ReservationSerializer
from core.serializers.saved_trip_serializer import SavedTripSerializer
from core.serializers.trip_click_serializer import TripClickSerializer
from core.serializers.trip_serializer import TripSerializer
from core.serializers.user_serializer import UserSerializer