# Generated by Django 4.1.3 on 2022-12-21 23:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tripclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripclick',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
