# Generated by Django 4.1.3 on 2022-12-27 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tripclick_datetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='Booking',
        ),
    ]
