# Generated by Django 4.1.3 on 2022-12-28 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_reservation_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hotel',
        ),
    ]
