name: Build and Push API Image to GitHub Container Registry

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
    - name: Build Image
      run: docker build --file api/Dockerfile --tag ghcr.io/aymaneboukrouh/tas-api:latest

    - name: Log In to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Image to GitHub Container Registry
      run: docker push ghcr.io/aymaneboukrouh/tas-api:latest
