name: Run API Tests

on:
  push:
    branches:
      - dev
    paths:
      - 'api/**'

  pull_request:
    branches:
      - dev
    paths:
      - 'api/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt
        
    - name: Run Tests
      run: |
        chmod +x scripts/*.sh
        python commands.py test
