name: Run API tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'web/**'
      - 'microservices/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'web/**'
      - 'microservices/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Run Tests
      run: |
        chmod +x scripts/*.sh
        ./scripts/test.sh
