name: Deploy to DigitalOcean

on:
  workflow_dispatch:

  workflow_run:
    workflows: ["Build and Push to GitHub Container Registry"]
    branches: [main]
    types:
      - completed

  push:
    branches: [main]
    paths:
      - '.github/workflows/deploy.yml'
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v2
        with:
          host: travel-agency-system.live
          private-key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        
      - name: Log In to GitHub Container Registry on DigitalOcean
        run: ssh root@travel-agency-system.live 'echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin'
      
      - name: Pull API Image from GitHub Container Registry
        run: ssh root@travel-agency-system.live 'docker pull ghcr.io/aymaneboukrouh/tas-api:latest'
      
      - name: Pull Web Image from GitHub Container Registry
        run: ssh root@travel-agency-system.live 'docker pull ghcr.io/aymaneboukrouh/tas-web:latest'
      
      - name: Copy docker-compose files to DigitalOcean
        run: |
          scp docker-compose.yml root@travel-agency-system.live:/home/tas/docker-compose.yml
          scp docker-compose.prod.yml root@travel-agency-system.live:/home/tas/docker-compose.prod.yml
      
      - name: Copy nginx config file to DigitalOcean
        run: scp nginx/nginx.conf root@travel-agency-system.live:/home/tas/nginx.conf

      - name: Run docker-compose on DigitalOcean
        run: ssh root@travel-agency-system.live 'docker compose -f /home/tas/docker-compose.yml -f /home/tas/docker-compose.prod.yml up -d'
